/* automatically generated by rust-bindgen */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
extern "C" {
    pub fn _convert_to_base62(
        base62: *mut ::std::os::raw::c_char,
        id: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @param base62 22 base62 character data. It doesn't have to be NUL-terminated,"]
    #[doc = "        but reading will stop if a NUL is found prematurely."]
    pub fn _convert_from_base62(
        id: *mut ::std::os::raw::c_char,
        base62: *const ::std::os::raw::c_char,
    ) -> bool;
}
