[package]
name = "rb62"
version = "0.1.0"
authors = ["Fuyang Liu <fuyangl@spotify.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
specialized-div-rem = "0.2.0"

[build-dependencies]
cc = "1.0"

