// Copyright (c) Spotify AB
// Beware: This file was generated by other/scripts/gen-base62-test-data.py
// Manual edits will be overwritten on next run.

// This file contains data used by unit tests for verification of our base62
// conversion implementations.
// All data have been generated using spotify-common, a python package used
// by backend for base62 conversions.

#pragma once

namespace spotify::tl::detail::test {

struct Base62TestData {
  const char *base62_rep;
  const char *hex_rep;
};

const int kNumBase62TestDatas = 617;
extern const Base62TestData g_base62_test_datas[kNumBase62TestDatas];

}  // namespace spotify::tl::detail::test
